dateModified: 1722193506
email:
  fromEmail: bramnijssen28@gmail.com
  fromName: 'Craft Assessment'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    3998564a-7b01-4066-9c15-b9a766c710e3: 'Craft Assessment' # Craft Assessment
    21268485-4977-439f-b7a6-1602eb471a66: 'Craft Assessment' # Craft Assessment
system:
  edition: solo
  live: true
  name: 'Craft Assessment'
  schemaVersion: 5.0.0.21
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
